-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity test_Hu_xFSobelFilter3x3_0_0_600_1024_1_0_0_1_2_2_2_1_1_1024_false_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    img_1_data65_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    img_1_data65_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    img_1_data65_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    img_1_data65_empty_n : IN STD_LOGIC;
    img_1_data65_read : OUT STD_LOGIC;
    img_2x_data66_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    img_2x_data66_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    img_2x_data66_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    img_2x_data66_full_n : IN STD_LOGIC;
    img_2x_data66_write : OUT STD_LOGIC;
    img_2y_data67_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    img_2y_data67_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    img_2y_data67_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    img_2y_data67_full_n : IN STD_LOGIC;
    img_2y_data67_write : OUT STD_LOGIC );
end;


architecture behav of test_Hu_xFSobelFilter3x3_0_0_600_1024_1_0_0_1_2_2_2_1_1_1024_false_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv13_2 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000010";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv10_259 : STD_LOGIC_VECTOR (9 downto 0) := "1001011001";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv10_258 : STD_LOGIC_VECTOR (9 downto 0) := "1001011000";
    constant ap_const_lv13_3 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal img_2x_data66_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal img_2y_data67_blk_n : STD_LOGIC;
    signal bottom_V_fu_261_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal bottom_V_reg_482 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln366_fu_207_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal mid_V_fu_292_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal mid_V_reg_487 : STD_LOGIC_VECTOR (1 downto 0);
    signal tp_V_fu_323_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tp_V_reg_492 : STD_LOGIC_VECTOR (1 downto 0);
    signal cmp_i_i603_i_fu_332_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_i_i603_i_reg_497 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_50_fu_339_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_50_reg_502 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_xFGradientX3x3_0_0_s_fu_169_ap_return : STD_LOGIC_VECTOR (7 downto 0);
    signal ref_tmp_reg_507 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal grp_xFGradientY3x3_0_0_s_fu_182_ap_return : STD_LOGIC_VECTOR (7 downto 0);
    signal ref_tmp1_reg_512 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_V_ce0 : STD_LOGIC;
    signal buf_V_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_V_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal buf_V_ce1 : STD_LOGIC;
    signal buf_V_we1 : STD_LOGIC;
    signal buf_V_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_V_1_ce0 : STD_LOGIC;
    signal buf_V_1_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_V_1_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal buf_V_1_ce1 : STD_LOGIC;
    signal buf_V_1_we1 : STD_LOGIC;
    signal buf_V_1_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_V_2_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_start : STD_LOGIC;
    signal grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_done : STD_LOGIC;
    signal grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_idle : STD_LOGIC;
    signal grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_ready : STD_LOGIC;
    signal grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_img_1_data65_read : STD_LOGIC;
    signal grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_1_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_1_ce1 : STD_LOGIC;
    signal grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_1_we1 : STD_LOGIC;
    signal grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_1_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_ce1 : STD_LOGIC;
    signal grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_we1 : STD_LOGIC;
    signal grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_start : STD_LOGIC;
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_done : STD_LOGIC;
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_idle : STD_LOGIC;
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_ready : STD_LOGIC;
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_1_data65_read : STD_LOGIC;
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_2x_data66_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_2x_data66_write : STD_LOGIC;
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_2y_data67_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_2y_data67_write : STD_LOGIC;
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_2_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_2_ce0 : STD_LOGIC;
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_2_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_2_ce1 : STD_LOGIC;
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_2_we1 : STD_LOGIC;
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_2_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_ce0 : STD_LOGIC;
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_ce1 : STD_LOGIC;
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_we1 : STD_LOGIC;
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_ce0 : STD_LOGIC;
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_ce1 : STD_LOGIC;
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_we1 : STD_LOGIC;
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_src_buf3_V_1_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_src_buf3_V_1_out_ap_vld : STD_LOGIC;
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_p_Val2_2_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_p_Val2_2_out_ap_vld : STD_LOGIC;
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_p_Val2_1_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_p_Val2_1_out_ap_vld : STD_LOGIC;
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_src_buf1_V_1_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_src_buf1_V_1_out_ap_vld : STD_LOGIC;
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_p_Val2_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_p_Val2_out_ap_vld : STD_LOGIC;
    signal grp_xFGradientX3x3_0_0_s_fu_169_ap_ce : STD_LOGIC;
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_xFGradientY3x3_0_0_s_fu_182_ap_ce : STD_LOGIC;
    signal grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal row_ind_V_fu_70 : STD_LOGIC_VECTOR (12 downto 0);
    signal row_ind_V_2_fu_356_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal row_V_fu_74 : STD_LOGIC_VECTOR (9 downto 0);
    signal row_V_3_fu_364_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tp_fu_78 : STD_LOGIC_VECTOR (1 downto 0);
    signal mid_fu_82 : STD_LOGIC_VECTOR (1 downto 0);
    signal bottom_fu_86 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_state8 : BOOLEAN;
    signal icmp_ln370_fu_225_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln370_2_fu_245_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln370_1_fu_239_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_45_fu_255_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_44_fu_251_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln370_fu_231_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_47_fu_286_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_46_fu_278_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln370_1_fu_270_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_49_fu_317_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_48_fu_309_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln370_2_fu_301_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal row_ind_V_1_fu_344_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln1019_fu_350_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component test_Hu_xFSobelFilter3x3_Pipeline_Clear_Row_Loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_1_data65_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_1_data65_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        img_1_data65_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        img_1_data65_empty_n : IN STD_LOGIC;
        img_1_data65_read : OUT STD_LOGIC;
        buf_V_1_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        buf_V_1_ce1 : OUT STD_LOGIC;
        buf_V_1_we1 : OUT STD_LOGIC;
        buf_V_1_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_V_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        buf_V_ce1 : OUT STD_LOGIC;
        buf_V_we1 : OUT STD_LOGIC;
        buf_V_d1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component test_Hu_xFSobelFilter3x3_Pipeline_Col_Loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_1_data65_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_1_data65_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        img_1_data65_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        img_1_data65_empty_n : IN STD_LOGIC;
        img_1_data65_read : OUT STD_LOGIC;
        img_2x_data66_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_2x_data66_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        img_2x_data66_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        img_2x_data66_full_n : IN STD_LOGIC;
        img_2x_data66_write : OUT STD_LOGIC;
        img_2y_data67_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_2y_data67_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        img_2y_data67_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        img_2y_data67_full_n : IN STD_LOGIC;
        img_2y_data67_write : OUT STD_LOGIC;
        tp_V : IN STD_LOGIC_VECTOR (1 downto 0);
        mid_V : IN STD_LOGIC_VECTOR (1 downto 0);
        bottom_V : IN STD_LOGIC_VECTOR (1 downto 0);
        row_ind_V_cast : IN STD_LOGIC_VECTOR (1 downto 0);
        buf_V_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        buf_V_2_ce0 : OUT STD_LOGIC;
        buf_V_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        buf_V_2_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        buf_V_2_ce1 : OUT STD_LOGIC;
        buf_V_2_we1 : OUT STD_LOGIC;
        buf_V_2_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_V_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        buf_V_1_ce0 : OUT STD_LOGIC;
        buf_V_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        buf_V_1_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        buf_V_1_ce1 : OUT STD_LOGIC;
        buf_V_1_we1 : OUT STD_LOGIC;
        buf_V_1_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        buf_V_ce0 : OUT STD_LOGIC;
        buf_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        buf_V_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        buf_V_ce1 : OUT STD_LOGIC;
        buf_V_we1 : OUT STD_LOGIC;
        buf_V_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        cmp_i_i603_i : IN STD_LOGIC_VECTOR (0 downto 0);
        src_buf3_V_1_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        src_buf3_V_1_out_ap_vld : OUT STD_LOGIC;
        p_Val2_2_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_Val2_2_out_ap_vld : OUT STD_LOGIC;
        p_Val2_1_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_Val2_1_out_ap_vld : OUT STD_LOGIC;
        src_buf1_V_1_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        src_buf1_V_1_out_ap_vld : OUT STD_LOGIC;
        p_Val2_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_Val2_out_ap_vld : OUT STD_LOGIC );
    end component;


    component test_Hu_xFGradientX3x3_0_0_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        t0 : IN STD_LOGIC_VECTOR (7 downto 0);
        t2 : IN STD_LOGIC_VECTOR (7 downto 0);
        m0 : IN STD_LOGIC_VECTOR (7 downto 0);
        m2 : IN STD_LOGIC_VECTOR (7 downto 0);
        b0 : IN STD_LOGIC_VECTOR (7 downto 0);
        b2 : IN STD_LOGIC_VECTOR (7 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_ce : IN STD_LOGIC );
    end component;


    component test_Hu_xFGradientY3x3_0_0_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        t0 : IN STD_LOGIC_VECTOR (7 downto 0);
        t1 : IN STD_LOGIC_VECTOR (7 downto 0);
        t2 : IN STD_LOGIC_VECTOR (7 downto 0);
        b0 : IN STD_LOGIC_VECTOR (7 downto 0);
        b1 : IN STD_LOGIC_VECTOR (7 downto 0);
        b2 : IN STD_LOGIC_VECTOR (7 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_ce : IN STD_LOGIC );
    end component;


    component test_Hu_xFSobelFilter3x3_0_0_600_1024_1_0_0_1_2_2_2_1_1_1024_false_s_buf_V_RAM_S2P_BRbkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    buf_V_U : component test_Hu_xFSobelFilter3x3_0_0_600_1024_1_0_0_1_2_2_2_1_1_1024_false_s_buf_V_RAM_S2P_BRbkb
    generic map (
        DataWidth => 8,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_address0,
        ce0 => buf_V_ce0,
        q0 => buf_V_q0,
        address1 => buf_V_address1,
        ce1 => buf_V_ce1,
        we1 => buf_V_we1,
        d1 => buf_V_d1);

    buf_V_1_U : component test_Hu_xFSobelFilter3x3_0_0_600_1024_1_0_0_1_2_2_2_1_1_1024_false_s_buf_V_RAM_S2P_BRbkb
    generic map (
        DataWidth => 8,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_address0,
        ce0 => buf_V_1_ce0,
        q0 => buf_V_1_q0,
        address1 => buf_V_1_address1,
        ce1 => buf_V_1_ce1,
        we1 => buf_V_1_we1,
        d1 => buf_V_1_d1);

    buf_V_2_U : component test_Hu_xFSobelFilter3x3_0_0_600_1024_1_0_0_1_2_2_2_1_1_1024_false_s_buf_V_RAM_S2P_BRbkb
    generic map (
        DataWidth => 8,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_2_address0,
        ce0 => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_2_ce0,
        q0 => buf_V_2_q0,
        address1 => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_2_address1,
        ce1 => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_2_ce1,
        we1 => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_2_we1,
        d1 => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_2_d1);

    grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136 : component test_Hu_xFSobelFilter3x3_Pipeline_Clear_Row_Loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_start,
        ap_done => grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_done,
        ap_idle => grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_idle,
        ap_ready => grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_ready,
        img_1_data65_dout => img_1_data65_dout,
        img_1_data65_num_data_valid => ap_const_lv2_0,
        img_1_data65_fifo_cap => ap_const_lv2_0,
        img_1_data65_empty_n => img_1_data65_empty_n,
        img_1_data65_read => grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_img_1_data65_read,
        buf_V_1_address1 => grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_1_address1,
        buf_V_1_ce1 => grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_1_ce1,
        buf_V_1_we1 => grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_1_we1,
        buf_V_1_d1 => grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_1_d1,
        buf_V_address1 => grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_address1,
        buf_V_ce1 => grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_ce1,
        buf_V_we1 => grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_we1,
        buf_V_d1 => grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_d1);

    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146 : component test_Hu_xFSobelFilter3x3_Pipeline_Col_Loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_start,
        ap_done => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_done,
        ap_idle => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_idle,
        ap_ready => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_ready,
        img_1_data65_dout => img_1_data65_dout,
        img_1_data65_num_data_valid => ap_const_lv2_0,
        img_1_data65_fifo_cap => ap_const_lv2_0,
        img_1_data65_empty_n => img_1_data65_empty_n,
        img_1_data65_read => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_1_data65_read,
        img_2x_data66_din => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_2x_data66_din,
        img_2x_data66_num_data_valid => ap_const_lv2_0,
        img_2x_data66_fifo_cap => ap_const_lv2_0,
        img_2x_data66_full_n => img_2x_data66_full_n,
        img_2x_data66_write => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_2x_data66_write,
        img_2y_data67_din => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_2y_data67_din,
        img_2y_data67_num_data_valid => ap_const_lv2_0,
        img_2y_data67_fifo_cap => ap_const_lv2_0,
        img_2y_data67_full_n => img_2y_data67_full_n,
        img_2y_data67_write => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_2y_data67_write,
        tp_V => tp_V_reg_492,
        mid_V => mid_V_reg_487,
        bottom_V => bottom_V_reg_482,
        row_ind_V_cast => empty_50_reg_502,
        buf_V_2_address0 => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_2_address0,
        buf_V_2_ce0 => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_2_ce0,
        buf_V_2_q0 => buf_V_2_q0,
        buf_V_2_address1 => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_2_address1,
        buf_V_2_ce1 => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_2_ce1,
        buf_V_2_we1 => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_2_we1,
        buf_V_2_d1 => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_2_d1,
        buf_V_1_address0 => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_address0,
        buf_V_1_ce0 => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_ce0,
        buf_V_1_q0 => buf_V_1_q0,
        buf_V_1_address1 => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_address1,
        buf_V_1_ce1 => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_ce1,
        buf_V_1_we1 => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_we1,
        buf_V_1_d1 => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_d1,
        buf_V_address0 => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_address0,
        buf_V_ce0 => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_ce0,
        buf_V_q0 => buf_V_q0,
        buf_V_address1 => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_address1,
        buf_V_ce1 => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_ce1,
        buf_V_we1 => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_we1,
        buf_V_d1 => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_d1,
        cmp_i_i603_i => cmp_i_i603_i_reg_497,
        src_buf3_V_1_out => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_src_buf3_V_1_out,
        src_buf3_V_1_out_ap_vld => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_src_buf3_V_1_out_ap_vld,
        p_Val2_2_out => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_p_Val2_2_out,
        p_Val2_2_out_ap_vld => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_p_Val2_2_out_ap_vld,
        p_Val2_1_out => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_p_Val2_1_out,
        p_Val2_1_out_ap_vld => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_p_Val2_1_out_ap_vld,
        src_buf1_V_1_out => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_src_buf1_V_1_out,
        src_buf1_V_1_out_ap_vld => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_src_buf1_V_1_out_ap_vld,
        p_Val2_out => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_p_Val2_out,
        p_Val2_out_ap_vld => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_p_Val2_out_ap_vld);

    grp_xFGradientX3x3_0_0_s_fu_169 : component test_Hu_xFGradientX3x3_0_0_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        t0 => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_p_Val2_out,
        t2 => ap_const_lv8_0,
        m0 => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_p_Val2_1_out,
        m2 => ap_const_lv8_0,
        b0 => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_p_Val2_2_out,
        b2 => ap_const_lv8_0,
        ap_return => grp_xFGradientX3x3_0_0_s_fu_169_ap_return,
        ap_ce => grp_xFGradientX3x3_0_0_s_fu_169_ap_ce);

    grp_xFGradientY3x3_0_0_s_fu_182 : component test_Hu_xFGradientY3x3_0_0_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        t0 => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_p_Val2_out,
        t1 => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_src_buf1_V_1_out,
        t2 => ap_const_lv8_0,
        b0 => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_p_Val2_2_out,
        b1 => grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_src_buf3_V_1_out,
        b2 => ap_const_lv8_0,
        ap_return => grp_xFGradientY3x3_0_0_s_fu_182_ap_return,
        ap_ce => grp_xFGradientY3x3_0_0_s_fu_182_ap_ce);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_ready = ap_const_logic_1)) then 
                    grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln366_fu_207_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_ready = ap_const_logic_1)) then 
                    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    row_V_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                row_V_fu_74 <= ap_const_lv10_1;
            elsif (((icmp_ln366_fu_207_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                row_V_fu_74 <= row_V_3_fu_364_p2;
            end if; 
        end if;
    end process;

    row_ind_V_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                row_ind_V_fu_70 <= ap_const_lv13_2;
            elsif (((icmp_ln366_fu_207_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                row_ind_V_fu_70 <= row_ind_V_2_fu_356_p3;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln366_fu_207_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                bottom_V_reg_482 <= bottom_V_fu_261_p3;
                bottom_fu_86 <= bottom_V_fu_261_p3;
                cmp_i_i603_i_reg_497 <= cmp_i_i603_i_fu_332_p2;
                empty_50_reg_502 <= empty_50_fu_339_p1;
                mid_V_reg_487 <= mid_V_fu_292_p3;
                mid_fu_82 <= mid_V_fu_292_p3;
                tp_V_reg_492 <= tp_V_fu_323_p3;
                tp_fu_78 <= tp_V_fu_323_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                ref_tmp1_reg_512 <= grp_xFGradientY3x3_0_0_s_fu_182_ap_return;
                ref_tmp_reg_507 <= grp_xFGradientX3x3_0_0_s_fu_169_ap_return;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, img_2x_data66_full_n, img_2y_data67_full_n, ap_CS_fsm_state8, ap_CS_fsm_state4, icmp_ln366_fu_207_p2, grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_done, grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state5)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((icmp_ln366_fu_207_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if ((not(((img_2y_data67_full_n = ap_const_logic_0) or (img_2x_data66_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_done)
    begin
        if ((grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_done)
    begin
        if ((grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(img_2x_data66_full_n, img_2y_data67_full_n)
    begin
        if (((img_2y_data67_full_n = ap_const_logic_0) or (img_2x_data66_full_n = ap_const_logic_0))) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state8_assign_proc : process(img_2x_data66_full_n, img_2y_data67_full_n)
    begin
                ap_block_state8 <= ((img_2y_data67_full_n = ap_const_logic_0) or (img_2x_data66_full_n = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state4, icmp_ln366_fu_207_p2)
    begin
        if ((((icmp_ln366_fu_207_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state4, icmp_ln366_fu_207_p2)
    begin
        if (((icmp_ln366_fu_207_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    bottom_V_fu_261_p3 <= 
        empty_44_fu_251_p1 when (empty_45_fu_255_p2(0) = '1') else 
        select_ln370_fu_231_p3;

    buf_V_1_address1_assign_proc : process(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_1_address1, grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_address1, ap_CS_fsm_state2, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            buf_V_1_address1 <= grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            buf_V_1_address1 <= grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_1_address1;
        else 
            buf_V_1_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    buf_V_1_ce0_assign_proc : process(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_ce0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            buf_V_1_ce0 <= grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_ce0;
        else 
            buf_V_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_1_ce1_assign_proc : process(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_1_ce1, grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_ce1, ap_CS_fsm_state2, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            buf_V_1_ce1 <= grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            buf_V_1_ce1 <= grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_1_ce1;
        else 
            buf_V_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_1_d1_assign_proc : process(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_1_d1, grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_d1, ap_CS_fsm_state2, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            buf_V_1_d1 <= grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_d1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            buf_V_1_d1 <= grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_1_d1;
        else 
            buf_V_1_d1 <= "XXXXXXXX";
        end if; 
    end process;


    buf_V_1_we1_assign_proc : process(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_1_we1, grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_we1, ap_CS_fsm_state2, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            buf_V_1_we1 <= grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_we1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            buf_V_1_we1 <= grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_1_we1;
        else 
            buf_V_1_we1 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_address1_assign_proc : process(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_address1, grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_address1, ap_CS_fsm_state2, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            buf_V_address1 <= grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            buf_V_address1 <= grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_address1;
        else 
            buf_V_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    buf_V_ce0_assign_proc : process(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_ce0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            buf_V_ce0 <= grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_ce0;
        else 
            buf_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_ce1_assign_proc : process(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_ce1, grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_ce1, ap_CS_fsm_state2, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            buf_V_ce1 <= grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            buf_V_ce1 <= grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_ce1;
        else 
            buf_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_d1_assign_proc : process(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_d1, grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_d1, ap_CS_fsm_state2, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            buf_V_d1 <= grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_d1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            buf_V_d1 <= grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_d1;
        else 
            buf_V_d1 <= "XXXXXXXX";
        end if; 
    end process;


    buf_V_we1_assign_proc : process(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_we1, grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_we1, ap_CS_fsm_state2, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            buf_V_we1 <= grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_we1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            buf_V_we1 <= grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_we1;
        else 
            buf_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    cmp_i_i603_i_fu_332_p2 <= "1" when (unsigned(row_V_fu_74) < unsigned(ap_const_lv10_258)) else "0";
    empty_44_fu_251_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln370_2_fu_245_p2),2));
    empty_45_fu_255_p2 <= (icmp_ln370_2_fu_245_p2 or icmp_ln370_1_fu_239_p2);
    empty_46_fu_278_p3 <= 
        ap_const_lv2_0 when (icmp_ln370_2_fu_245_p2(0) = '1') else 
        ap_const_lv2_2;
    empty_47_fu_286_p2 <= (icmp_ln370_2_fu_245_p2 or icmp_ln370_1_fu_239_p2);
    empty_48_fu_309_p3 <= 
        ap_const_lv2_2 when (icmp_ln370_2_fu_245_p2(0) = '1') else 
        ap_const_lv2_1;
    empty_49_fu_317_p2 <= (icmp_ln370_2_fu_245_p2 or icmp_ln370_1_fu_239_p2);
    empty_50_fu_339_p1 <= row_ind_V_fu_70(2 - 1 downto 0);

    grp_xFGradientX3x3_0_0_s_fu_169_ap_ce_assign_proc : process(ap_CS_fsm_state7, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            grp_xFGradientX3x3_0_0_s_fu_169_ap_ce <= ap_const_logic_1;
        else 
            grp_xFGradientX3x3_0_0_s_fu_169_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_xFGradientY3x3_0_0_s_fu_182_ap_ce_assign_proc : process(ap_CS_fsm_state7, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            grp_xFGradientY3x3_0_0_s_fu_182_ap_ce <= ap_const_logic_1;
        else 
            grp_xFGradientY3x3_0_0_s_fu_182_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_start <= grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_start_reg;
    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_start <= grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_start_reg;
    icmp_ln1019_fu_350_p2 <= "1" when (row_ind_V_1_fu_344_p2 = ap_const_lv13_3) else "0";
    icmp_ln366_fu_207_p2 <= "1" when (row_V_fu_74 = ap_const_lv10_259) else "0";
    icmp_ln370_1_fu_239_p2 <= "1" when (row_ind_V_fu_70 = ap_const_lv13_0) else "0";
    icmp_ln370_2_fu_245_p2 <= "1" when (row_ind_V_fu_70 = ap_const_lv13_1) else "0";
    icmp_ln370_fu_225_p2 <= "1" when (row_ind_V_fu_70 = ap_const_lv13_2) else "0";

    img_1_data65_read_assign_proc : process(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_img_1_data65_read, grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_1_data65_read, ap_CS_fsm_state2, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            img_1_data65_read <= grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_1_data65_read;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            img_1_data65_read <= grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_img_1_data65_read;
        else 
            img_1_data65_read <= ap_const_logic_0;
        end if; 
    end process;


    img_2x_data66_blk_n_assign_proc : process(img_2x_data66_full_n, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            img_2x_data66_blk_n <= img_2x_data66_full_n;
        else 
            img_2x_data66_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    img_2x_data66_din_assign_proc : process(img_2x_data66_full_n, img_2y_data67_full_n, ap_CS_fsm_state8, ref_tmp_reg_507, grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_2x_data66_din, ap_CS_fsm_state5)
    begin
        if ((not(((img_2y_data67_full_n = ap_const_logic_0) or (img_2x_data66_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            img_2x_data66_din <= ref_tmp_reg_507;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            img_2x_data66_din <= grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_2x_data66_din;
        else 
            img_2x_data66_din <= grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_2x_data66_din;
        end if; 
    end process;


    img_2x_data66_write_assign_proc : process(img_2x_data66_full_n, img_2y_data67_full_n, ap_CS_fsm_state8, grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_2x_data66_write, ap_CS_fsm_state5)
    begin
        if ((not(((img_2y_data67_full_n = ap_const_logic_0) or (img_2x_data66_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            img_2x_data66_write <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            img_2x_data66_write <= grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_2x_data66_write;
        else 
            img_2x_data66_write <= ap_const_logic_0;
        end if; 
    end process;


    img_2y_data67_blk_n_assign_proc : process(img_2y_data67_full_n, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            img_2y_data67_blk_n <= img_2y_data67_full_n;
        else 
            img_2y_data67_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    img_2y_data67_din_assign_proc : process(img_2x_data66_full_n, img_2y_data67_full_n, ap_CS_fsm_state8, ref_tmp1_reg_512, grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_2y_data67_din, ap_CS_fsm_state5)
    begin
        if ((not(((img_2y_data67_full_n = ap_const_logic_0) or (img_2x_data66_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            img_2y_data67_din <= ref_tmp1_reg_512;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            img_2y_data67_din <= grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_2y_data67_din;
        else 
            img_2y_data67_din <= grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_2y_data67_din;
        end if; 
    end process;


    img_2y_data67_write_assign_proc : process(img_2x_data66_full_n, img_2y_data67_full_n, ap_CS_fsm_state8, grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_2y_data67_write, ap_CS_fsm_state5)
    begin
        if ((not(((img_2y_data67_full_n = ap_const_logic_0) or (img_2x_data66_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            img_2y_data67_write <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            img_2y_data67_write <= grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_2y_data67_write;
        else 
            img_2y_data67_write <= ap_const_logic_0;
        end if; 
    end process;

    mid_V_fu_292_p3 <= 
        empty_46_fu_278_p3 when (empty_47_fu_286_p2(0) = '1') else 
        select_ln370_1_fu_270_p3;
    row_V_3_fu_364_p2 <= std_logic_vector(unsigned(row_V_fu_74) + unsigned(ap_const_lv10_1));
    row_ind_V_1_fu_344_p2 <= std_logic_vector(unsigned(row_ind_V_fu_70) + unsigned(ap_const_lv13_1));
    row_ind_V_2_fu_356_p3 <= 
        ap_const_lv13_0 when (icmp_ln1019_fu_350_p2(0) = '1') else 
        row_ind_V_1_fu_344_p2;
    select_ln370_1_fu_270_p3 <= 
        ap_const_lv2_1 when (icmp_ln370_fu_225_p2(0) = '1') else 
        mid_fu_82;
    select_ln370_2_fu_301_p3 <= 
        ap_const_lv2_0 when (icmp_ln370_fu_225_p2(0) = '1') else 
        tp_fu_78;
    select_ln370_fu_231_p3 <= 
        ap_const_lv2_2 when (icmp_ln370_fu_225_p2(0) = '1') else 
        bottom_fu_86;
    tp_V_fu_323_p3 <= 
        empty_48_fu_309_p3 when (empty_49_fu_317_p2(0) = '1') else 
        select_ln370_2_fu_301_p3;
end behav;
