// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module test_Hu_xFGradientY3x3_0_0_s (
        ap_clk,
        ap_rst,
        t0,
        t1,
        t2,
        b0,
        b1,
        b2,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [7:0] t0;
input  [7:0] t1;
input  [7:0] t2;
input  [7:0] b0;
input  [7:0] b1;
input  [7:0] b2;
output  [7:0] ap_return;
input   ap_ce;

reg[7:0] ap_return;

wire   [8:0] ret_V_fu_102_p2;
reg   [8:0] ret_V_reg_205;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [8:0] ret_V_8_fu_116_p2;
reg   [8:0] ret_V_8_reg_210;
wire   [9:0] out_pix_3_fu_122_p2;
reg   [9:0] out_pix_3_reg_215;
wire    ap_block_pp0_stage0;
wire   [8:0] M00_fu_70_p3;
wire   [8:0] M01_fu_82_p3;
wire   [8:0] zext_ln186_1_fu_98_p1;
wire   [8:0] zext_ln186_fu_94_p1;
wire   [8:0] zext_ln186_3_fu_112_p1;
wire   [8:0] zext_ln186_2_fu_108_p1;
wire   [9:0] zext_ln108_fu_90_p1;
wire   [9:0] zext_ln107_fu_78_p1;
wire  signed [10:0] sext_ln114_fu_134_p1;
wire   [10:0] zext_ln109_fu_128_p1;
wire   [10:0] out_pix_4_fu_137_p2;
wire   [10:0] zext_ln110_fu_131_p1;
wire   [10:0] out_pix_fu_143_p2;
wire   [2:0] tmp_5_fu_161_p4;
wire   [0:0] tmp_fu_153_p3;
wire   [0:0] xor_ln120_fu_177_p2;
wire   [0:0] icmp_ln122_fu_171_p2;
wire   [0:0] or_ln120_fu_191_p2;
wire   [7:0] select_ln120_fu_183_p3;
wire   [7:0] trunc_ln212_fu_149_p1;
wire   [7:0] select_ln120_1_fu_197_p3;
reg    ap_ce_reg;
reg   [7:0] ap_return_int_reg;

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= select_ln120_1_fu_197_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1))) begin
        out_pix_3_reg_215[9 : 1] <= out_pix_3_fu_122_p2[9 : 1];
        ret_V_8_reg_210 <= ret_V_8_fu_116_p2;
        ret_V_reg_205 <= ret_V_fu_102_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = select_ln120_1_fu_197_p3;
    end else begin
        ap_return = 'bx;
    end
end

assign M00_fu_70_p3 = {{t1}, {1'd0}};

assign M01_fu_82_p3 = {{b1}, {1'd0}};

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign icmp_ln122_fu_171_p2 = (($signed(tmp_5_fu_161_p4) > $signed(3'd0)) ? 1'b1 : 1'b0);

assign or_ln120_fu_191_p2 = (tmp_fu_153_p3 | icmp_ln122_fu_171_p2);

assign out_pix_3_fu_122_p2 = (zext_ln108_fu_90_p1 - zext_ln107_fu_78_p1);

assign out_pix_4_fu_137_p2 = ($signed(sext_ln114_fu_134_p1) + $signed(zext_ln109_fu_128_p1));

assign out_pix_fu_143_p2 = (out_pix_4_fu_137_p2 - zext_ln110_fu_131_p1);

assign ret_V_8_fu_116_p2 = (zext_ln186_3_fu_112_p1 + zext_ln186_2_fu_108_p1);

assign ret_V_fu_102_p2 = (zext_ln186_1_fu_98_p1 + zext_ln186_fu_94_p1);

assign select_ln120_1_fu_197_p3 = ((or_ln120_fu_191_p2[0:0] == 1'b1) ? select_ln120_fu_183_p3 : trunc_ln212_fu_149_p1);

assign select_ln120_fu_183_p3 = ((xor_ln120_fu_177_p2[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign sext_ln114_fu_134_p1 = $signed(out_pix_3_reg_215);

assign tmp_5_fu_161_p4 = {{out_pix_fu_143_p2[10:8]}};

assign tmp_fu_153_p3 = out_pix_fu_143_p2[32'd10];

assign trunc_ln212_fu_149_p1 = out_pix_fu_143_p2[7:0];

assign xor_ln120_fu_177_p2 = (tmp_fu_153_p3 ^ 1'd1);

assign zext_ln107_fu_78_p1 = M00_fu_70_p3;

assign zext_ln108_fu_90_p1 = M01_fu_82_p3;

assign zext_ln109_fu_128_p1 = ret_V_reg_205;

assign zext_ln110_fu_131_p1 = ret_V_8_reg_210;

assign zext_ln186_1_fu_98_p1 = b2;

assign zext_ln186_2_fu_108_p1 = t0;

assign zext_ln186_3_fu_112_p1 = t2;

assign zext_ln186_fu_94_p1 = b0;

always @ (posedge ap_clk) begin
    out_pix_3_reg_215[0] <= 1'b0;
end

endmodule //test_Hu_xFGradientY3x3_0_0_s
