// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module test_Hu_xFSobelFilter3x3_0_0_600_1024_1_0_0_1_2_2_2_1_1_1024_false_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        img_1_data65_dout,
        img_1_data65_num_data_valid,
        img_1_data65_fifo_cap,
        img_1_data65_empty_n,
        img_1_data65_read,
        img_2x_data66_din,
        img_2x_data66_num_data_valid,
        img_2x_data66_fifo_cap,
        img_2x_data66_full_n,
        img_2x_data66_write,
        img_2y_data67_din,
        img_2y_data67_num_data_valid,
        img_2y_data67_fifo_cap,
        img_2y_data67_full_n,
        img_2y_data67_write
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] img_1_data65_dout;
input  [1:0] img_1_data65_num_data_valid;
input  [1:0] img_1_data65_fifo_cap;
input   img_1_data65_empty_n;
output   img_1_data65_read;
output  [7:0] img_2x_data66_din;
input  [1:0] img_2x_data66_num_data_valid;
input  [1:0] img_2x_data66_fifo_cap;
input   img_2x_data66_full_n;
output   img_2x_data66_write;
output  [7:0] img_2y_data67_din;
input  [1:0] img_2y_data67_num_data_valid;
input  [1:0] img_2y_data67_fifo_cap;
input   img_2y_data67_full_n;
output   img_2y_data67_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg img_1_data65_read;
reg[7:0] img_2x_data66_din;
reg img_2x_data66_write;
reg[7:0] img_2y_data67_din;
reg img_2y_data67_write;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    img_2x_data66_blk_n;
wire    ap_CS_fsm_state8;
reg    img_2y_data67_blk_n;
wire   [1:0] bottom_V_fu_261_p3;
reg   [1:0] bottom_V_reg_482;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln366_fu_207_p2;
wire   [1:0] mid_V_fu_292_p3;
reg   [1:0] mid_V_reg_487;
wire   [1:0] tp_V_fu_323_p3;
reg   [1:0] tp_V_reg_492;
wire   [0:0] cmp_i_i603_i_fu_332_p2;
reg   [0:0] cmp_i_i603_i_reg_497;
wire   [1:0] empty_50_fu_339_p1;
reg   [1:0] empty_50_reg_502;
wire   [7:0] grp_xFGradientX3x3_0_0_s_fu_169_ap_return;
reg   [7:0] ref_tmp_reg_507;
wire    ap_CS_fsm_state7;
wire   [7:0] grp_xFGradientY3x3_0_0_s_fu_182_ap_return;
reg   [7:0] ref_tmp1_reg_512;
reg    buf_V_ce0;
wire   [7:0] buf_V_q0;
reg   [9:0] buf_V_address1;
reg    buf_V_ce1;
reg    buf_V_we1;
reg   [7:0] buf_V_d1;
reg    buf_V_1_ce0;
wire   [7:0] buf_V_1_q0;
reg   [9:0] buf_V_1_address1;
reg    buf_V_1_ce1;
reg    buf_V_1_we1;
reg   [7:0] buf_V_1_d1;
wire   [7:0] buf_V_2_q0;
wire    grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_start;
wire    grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_done;
wire    grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_idle;
wire    grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_ready;
wire    grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_img_1_data65_read;
wire   [9:0] grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_1_address1;
wire    grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_1_ce1;
wire    grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_1_we1;
wire   [7:0] grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_1_d1;
wire   [9:0] grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_address1;
wire    grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_ce1;
wire    grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_we1;
wire   [7:0] grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_d1;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_start;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_done;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_idle;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_ready;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_1_data65_read;
wire   [7:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_2x_data66_din;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_2x_data66_write;
wire   [7:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_2y_data67_din;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_2y_data67_write;
wire   [9:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_2_address0;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_2_ce0;
wire   [9:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_2_address1;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_2_ce1;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_2_we1;
wire   [7:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_2_d1;
wire   [9:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_address0;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_ce0;
wire   [9:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_address1;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_ce1;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_we1;
wire   [7:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_d1;
wire   [9:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_address0;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_ce0;
wire   [9:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_address1;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_ce1;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_we1;
wire   [7:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_d1;
wire   [7:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_src_buf3_V_1_out;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_src_buf3_V_1_out_ap_vld;
wire   [7:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_p_Val2_2_out;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_p_Val2_2_out_ap_vld;
wire   [7:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_p_Val2_1_out;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_p_Val2_1_out_ap_vld;
wire   [7:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_src_buf1_V_1_out;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_src_buf1_V_1_out_ap_vld;
wire   [7:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_p_Val2_out;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_p_Val2_out_ap_vld;
reg    grp_xFGradientX3x3_0_0_s_fu_169_ap_ce;
wire    ap_CS_fsm_state6;
reg    grp_xFGradientY3x3_0_0_s_fu_182_ap_ce;
reg    grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_start_reg;
wire    ap_CS_fsm_state5;
reg   [12:0] row_ind_V_fu_70;
wire   [12:0] row_ind_V_2_fu_356_p3;
reg   [9:0] row_V_fu_74;
wire   [9:0] row_V_3_fu_364_p2;
reg   [1:0] tp_fu_78;
reg   [1:0] mid_fu_82;
reg   [1:0] bottom_fu_86;
reg    ap_block_state8;
wire   [0:0] icmp_ln370_fu_225_p2;
wire   [0:0] icmp_ln370_2_fu_245_p2;
wire   [0:0] icmp_ln370_1_fu_239_p2;
wire   [0:0] empty_45_fu_255_p2;
wire   [1:0] empty_44_fu_251_p1;
wire   [1:0] select_ln370_fu_231_p3;
wire   [0:0] empty_47_fu_286_p2;
wire   [1:0] empty_46_fu_278_p3;
wire   [1:0] select_ln370_1_fu_270_p3;
wire   [0:0] empty_49_fu_317_p2;
wire   [1:0] empty_48_fu_309_p3;
wire   [1:0] select_ln370_2_fu_301_p3;
wire   [12:0] row_ind_V_1_fu_344_p2;
wire   [0:0] icmp_ln1019_fu_350_p2;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_start_reg = 1'b0;
#0 grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_start_reg = 1'b0;
end

test_Hu_xFSobelFilter3x3_0_0_600_1024_1_0_0_1_2_2_2_1_1_1024_false_s_buf_V_RAM_S2P_BRbkb #(
    .DataWidth( 8 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
buf_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_address0),
    .ce0(buf_V_ce0),
    .q0(buf_V_q0),
    .address1(buf_V_address1),
    .ce1(buf_V_ce1),
    .we1(buf_V_we1),
    .d1(buf_V_d1)
);

test_Hu_xFSobelFilter3x3_0_0_600_1024_1_0_0_1_2_2_2_1_1_1024_false_s_buf_V_RAM_S2P_BRbkb #(
    .DataWidth( 8 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
buf_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_address0),
    .ce0(buf_V_1_ce0),
    .q0(buf_V_1_q0),
    .address1(buf_V_1_address1),
    .ce1(buf_V_1_ce1),
    .we1(buf_V_1_we1),
    .d1(buf_V_1_d1)
);

test_Hu_xFSobelFilter3x3_0_0_600_1024_1_0_0_1_2_2_2_1_1_1024_false_s_buf_V_RAM_S2P_BRbkb #(
    .DataWidth( 8 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
buf_V_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_2_address0),
    .ce0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_2_ce0),
    .q0(buf_V_2_q0),
    .address1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_2_address1),
    .ce1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_2_ce1),
    .we1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_2_we1),
    .d1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_2_d1)
);

test_Hu_xFSobelFilter3x3_Pipeline_Clear_Row_Loop grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_start),
    .ap_done(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_done),
    .ap_idle(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_idle),
    .ap_ready(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_ready),
    .img_1_data65_dout(img_1_data65_dout),
    .img_1_data65_num_data_valid(2'd0),
    .img_1_data65_fifo_cap(2'd0),
    .img_1_data65_empty_n(img_1_data65_empty_n),
    .img_1_data65_read(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_img_1_data65_read),
    .buf_V_1_address1(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_1_address1),
    .buf_V_1_ce1(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_1_ce1),
    .buf_V_1_we1(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_1_we1),
    .buf_V_1_d1(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_1_d1),
    .buf_V_address1(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_address1),
    .buf_V_ce1(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_ce1),
    .buf_V_we1(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_we1),
    .buf_V_d1(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_d1)
);

test_Hu_xFSobelFilter3x3_Pipeline_Col_Loop grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_start),
    .ap_done(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_done),
    .ap_idle(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_idle),
    .ap_ready(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_ready),
    .img_1_data65_dout(img_1_data65_dout),
    .img_1_data65_num_data_valid(2'd0),
    .img_1_data65_fifo_cap(2'd0),
    .img_1_data65_empty_n(img_1_data65_empty_n),
    .img_1_data65_read(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_1_data65_read),
    .img_2x_data66_din(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_2x_data66_din),
    .img_2x_data66_num_data_valid(2'd0),
    .img_2x_data66_fifo_cap(2'd0),
    .img_2x_data66_full_n(img_2x_data66_full_n),
    .img_2x_data66_write(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_2x_data66_write),
    .img_2y_data67_din(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_2y_data67_din),
    .img_2y_data67_num_data_valid(2'd0),
    .img_2y_data67_fifo_cap(2'd0),
    .img_2y_data67_full_n(img_2y_data67_full_n),
    .img_2y_data67_write(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_2y_data67_write),
    .tp_V(tp_V_reg_492),
    .mid_V(mid_V_reg_487),
    .bottom_V(bottom_V_reg_482),
    .row_ind_V_cast(empty_50_reg_502),
    .buf_V_2_address0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_2_address0),
    .buf_V_2_ce0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_2_ce0),
    .buf_V_2_q0(buf_V_2_q0),
    .buf_V_2_address1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_2_address1),
    .buf_V_2_ce1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_2_ce1),
    .buf_V_2_we1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_2_we1),
    .buf_V_2_d1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_2_d1),
    .buf_V_1_address0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_address0),
    .buf_V_1_ce0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_ce0),
    .buf_V_1_q0(buf_V_1_q0),
    .buf_V_1_address1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_address1),
    .buf_V_1_ce1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_ce1),
    .buf_V_1_we1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_we1),
    .buf_V_1_d1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_d1),
    .buf_V_address0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_address0),
    .buf_V_ce0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_ce0),
    .buf_V_q0(buf_V_q0),
    .buf_V_address1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_address1),
    .buf_V_ce1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_ce1),
    .buf_V_we1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_we1),
    .buf_V_d1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_d1),
    .cmp_i_i603_i(cmp_i_i603_i_reg_497),
    .src_buf3_V_1_out(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_src_buf3_V_1_out),
    .src_buf3_V_1_out_ap_vld(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_src_buf3_V_1_out_ap_vld),
    .p_Val2_2_out(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_p_Val2_2_out),
    .p_Val2_2_out_ap_vld(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_p_Val2_2_out_ap_vld),
    .p_Val2_1_out(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_p_Val2_1_out),
    .p_Val2_1_out_ap_vld(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_p_Val2_1_out_ap_vld),
    .src_buf1_V_1_out(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_src_buf1_V_1_out),
    .src_buf1_V_1_out_ap_vld(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_src_buf1_V_1_out_ap_vld),
    .p_Val2_out(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_p_Val2_out),
    .p_Val2_out_ap_vld(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_p_Val2_out_ap_vld)
);

test_Hu_xFGradientX3x3_0_0_s grp_xFGradientX3x3_0_0_s_fu_169(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .t0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_p_Val2_out),
    .t2(8'd0),
    .m0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_p_Val2_1_out),
    .m2(8'd0),
    .b0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_p_Val2_2_out),
    .b2(8'd0),
    .ap_return(grp_xFGradientX3x3_0_0_s_fu_169_ap_return),
    .ap_ce(grp_xFGradientX3x3_0_0_s_fu_169_ap_ce)
);

test_Hu_xFGradientY3x3_0_0_s grp_xFGradientY3x3_0_0_s_fu_182(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .t0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_p_Val2_out),
    .t1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_src_buf1_V_1_out),
    .t2(8'd0),
    .b0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_p_Val2_2_out),
    .b1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_src_buf3_V_1_out),
    .b2(8'd0),
    .ap_return(grp_xFGradientY3x3_0_0_s_fu_182_ap_return),
    .ap_ce(grp_xFGradientY3x3_0_0_s_fu_182_ap_ce)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_start_reg <= 1'b1;
        end else if ((grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_ready == 1'b1)) begin
            grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln366_fu_207_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
            grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_start_reg <= 1'b1;
        end else if ((grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_ready == 1'b1)) begin
            grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        row_V_fu_74 <= 10'd1;
    end else if (((icmp_ln366_fu_207_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        row_V_fu_74 <= row_V_3_fu_364_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        row_ind_V_fu_70 <= 13'd2;
    end else if (((icmp_ln366_fu_207_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        row_ind_V_fu_70 <= row_ind_V_2_fu_356_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln366_fu_207_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        bottom_V_reg_482 <= bottom_V_fu_261_p3;
        bottom_fu_86 <= bottom_V_fu_261_p3;
        cmp_i_i603_i_reg_497 <= cmp_i_i603_i_fu_332_p2;
        empty_50_reg_502 <= empty_50_fu_339_p1;
        mid_V_reg_487 <= mid_V_fu_292_p3;
        mid_fu_82 <= mid_V_fu_292_p3;
        tp_V_reg_492 <= tp_V_fu_323_p3;
        tp_fu_78 <= tp_V_fu_323_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ref_tmp1_reg_512 <= grp_xFGradientY3x3_0_0_s_fu_182_ap_return;
        ref_tmp_reg_507 <= grp_xFGradientX3x3_0_0_s_fu_169_ap_return;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if (((img_2y_data67_full_n == 1'b0) | (img_2x_data66_full_n == 1'b0))) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln366_fu_207_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln366_fu_207_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_V_1_address1 = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_address1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_1_address1 = grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_1_address1;
    end else begin
        buf_V_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_V_1_ce0 = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_ce0;
    end else begin
        buf_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_V_1_ce1 = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_ce1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_1_ce1 = grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_1_ce1;
    end else begin
        buf_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_V_1_d1 = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_d1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_1_d1 = grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_1_d1;
    end else begin
        buf_V_1_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_V_1_we1 = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_1_we1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_1_we1 = grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_1_we1;
    end else begin
        buf_V_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_V_address1 = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_address1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_address1 = grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_address1;
    end else begin
        buf_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_V_ce0 = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_ce0;
    end else begin
        buf_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_V_ce1 = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_ce1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_ce1 = grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_ce1;
    end else begin
        buf_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_V_d1 = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_d1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_d1 = grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_d1;
    end else begin
        buf_V_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_V_we1 = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_buf_V_we1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_we1 = grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_buf_V_we1;
    end else begin
        buf_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6))) begin
        grp_xFGradientX3x3_0_0_s_fu_169_ap_ce = 1'b1;
    end else begin
        grp_xFGradientX3x3_0_0_s_fu_169_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6))) begin
        grp_xFGradientY3x3_0_0_s_fu_182_ap_ce = 1'b1;
    end else begin
        grp_xFGradientY3x3_0_0_s_fu_182_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        img_1_data65_read = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_1_data65_read;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        img_1_data65_read = grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_img_1_data65_read;
    end else begin
        img_1_data65_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        img_2x_data66_blk_n = img_2x_data66_full_n;
    end else begin
        img_2x_data66_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((img_2y_data67_full_n == 1'b0) | (img_2x_data66_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state8))) begin
        img_2x_data66_din = ref_tmp_reg_507;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        img_2x_data66_din = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_2x_data66_din;
    end else begin
        img_2x_data66_din = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_2x_data66_din;
    end
end

always @ (*) begin
    if ((~((img_2y_data67_full_n == 1'b0) | (img_2x_data66_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state8))) begin
        img_2x_data66_write = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        img_2x_data66_write = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_2x_data66_write;
    end else begin
        img_2x_data66_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        img_2y_data67_blk_n = img_2y_data67_full_n;
    end else begin
        img_2y_data67_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((img_2y_data67_full_n == 1'b0) | (img_2x_data66_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state8))) begin
        img_2y_data67_din = ref_tmp1_reg_512;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        img_2y_data67_din = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_2y_data67_din;
    end else begin
        img_2y_data67_din = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_2y_data67_din;
    end
end

always @ (*) begin
    if ((~((img_2y_data67_full_n == 1'b0) | (img_2x_data66_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state8))) begin
        img_2y_data67_write = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        img_2y_data67_write = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_img_2y_data67_write;
    end else begin
        img_2y_data67_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln366_fu_207_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if ((~((img_2y_data67_full_n == 1'b0) | (img_2x_data66_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

always @ (*) begin
    ap_block_state8 = ((img_2y_data67_full_n == 1'b0) | (img_2x_data66_full_n == 1'b0));
end

assign bottom_V_fu_261_p3 = ((empty_45_fu_255_p2[0:0] == 1'b1) ? empty_44_fu_251_p1 : select_ln370_fu_231_p3);

assign cmp_i_i603_i_fu_332_p2 = ((row_V_fu_74 < 10'd600) ? 1'b1 : 1'b0);

assign empty_44_fu_251_p1 = icmp_ln370_2_fu_245_p2;

assign empty_45_fu_255_p2 = (icmp_ln370_2_fu_245_p2 | icmp_ln370_1_fu_239_p2);

assign empty_46_fu_278_p3 = ((icmp_ln370_2_fu_245_p2[0:0] == 1'b1) ? 2'd0 : 2'd2);

assign empty_47_fu_286_p2 = (icmp_ln370_2_fu_245_p2 | icmp_ln370_1_fu_239_p2);

assign empty_48_fu_309_p3 = ((icmp_ln370_2_fu_245_p2[0:0] == 1'b1) ? 2'd2 : 2'd1);

assign empty_49_fu_317_p2 = (icmp_ln370_2_fu_245_p2 | icmp_ln370_1_fu_239_p2);

assign empty_50_fu_339_p1 = row_ind_V_fu_70[1:0];

assign grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_start = grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_136_ap_start_reg;

assign grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_start = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_146_ap_start_reg;

assign icmp_ln1019_fu_350_p2 = ((row_ind_V_1_fu_344_p2 == 13'd3) ? 1'b1 : 1'b0);

assign icmp_ln366_fu_207_p2 = ((row_V_fu_74 == 10'd601) ? 1'b1 : 1'b0);

assign icmp_ln370_1_fu_239_p2 = ((row_ind_V_fu_70 == 13'd0) ? 1'b1 : 1'b0);

assign icmp_ln370_2_fu_245_p2 = ((row_ind_V_fu_70 == 13'd1) ? 1'b1 : 1'b0);

assign icmp_ln370_fu_225_p2 = ((row_ind_V_fu_70 == 13'd2) ? 1'b1 : 1'b0);

assign mid_V_fu_292_p3 = ((empty_47_fu_286_p2[0:0] == 1'b1) ? empty_46_fu_278_p3 : select_ln370_1_fu_270_p3);

assign row_V_3_fu_364_p2 = (row_V_fu_74 + 10'd1);

assign row_ind_V_1_fu_344_p2 = (row_ind_V_fu_70 + 13'd1);

assign row_ind_V_2_fu_356_p3 = ((icmp_ln1019_fu_350_p2[0:0] == 1'b1) ? 13'd0 : row_ind_V_1_fu_344_p2);

assign select_ln370_1_fu_270_p3 = ((icmp_ln370_fu_225_p2[0:0] == 1'b1) ? 2'd1 : mid_fu_82);

assign select_ln370_2_fu_301_p3 = ((icmp_ln370_fu_225_p2[0:0] == 1'b1) ? 2'd0 : tp_fu_78);

assign select_ln370_fu_231_p3 = ((icmp_ln370_fu_225_p2[0:0] == 1'b1) ? 2'd2 : bottom_fu_86);

assign tp_V_fu_323_p3 = ((empty_49_fu_317_p2[0:0] == 1'b1) ? empty_48_fu_309_p3 : select_ln370_2_fu_301_p3);

endmodule //test_Hu_xFSobelFilter3x3_0_0_600_1024_1_0_0_1_2_2_2_1_1_1024_false_s
