-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity color_analysis_xferode_600_1024_1_0_1_2_2_0_1025_3_3_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    img_2_data165_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    img_2_data165_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    img_2_data165_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    img_2_data165_empty_n : IN STD_LOGIC;
    img_2_data165_read : OUT STD_LOGIC;
    img_3_data166_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    img_3_data166_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    img_3_data166_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    img_3_data166_full_n : IN STD_LOGIC;
    img_3_data166_write : OUT STD_LOGIC;
    img_height : IN STD_LOGIC_VECTOR (15 downto 0);
    img_width : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of color_analysis_xferode_600_1024_1_0_1_2_2_0_1025_3_3_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_ln1027_fu_180_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1027_reg_344 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_i_i142_i_fu_257_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_i_i142_i_reg_389 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal icmp_ln1027_3_fu_249_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_53_fu_263_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_53_reg_394 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_54_fu_268_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_54_reg_399 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_55_fu_273_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_55_reg_404 : STD_LOGIC_VECTOR (1 downto 0);
    signal buf_V_ce0 : STD_LOGIC;
    signal buf_V_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_V_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal buf_V_ce1 : STD_LOGIC;
    signal buf_V_we1 : STD_LOGIC;
    signal buf_V_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_V_1_ce0 : STD_LOGIC;
    signal buf_V_1_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_V_1_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal buf_V_1_ce1 : STD_LOGIC;
    signal buf_V_1_we1 : STD_LOGIC;
    signal buf_V_1_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_V_2_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1_fu_139_ap_start : STD_LOGIC;
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1_fu_139_ap_done : STD_LOGIC;
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1_fu_139_ap_idle : STD_LOGIC;
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1_fu_139_ap_ready : STD_LOGIC;
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1_fu_139_row_ind_V_2_out : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1_fu_139_row_ind_V_2_out_ap_vld : STD_LOGIC;
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1_fu_139_row_ind_V_1_out : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1_fu_139_row_ind_V_1_out_ap_vld : STD_LOGIC;
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1_fu_139_row_ind_V_out : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1_fu_139_row_ind_V_out_ap_vld : STD_LOGIC;
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_ap_start : STD_LOGIC;
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_ap_done : STD_LOGIC;
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_ap_idle : STD_LOGIC;
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_ap_ready : STD_LOGIC;
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_img_2_data165_read : STD_LOGIC;
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_buf_V_1_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_buf_V_1_ce1 : STD_LOGIC;
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_buf_V_1_we1 : STD_LOGIC;
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_buf_V_1_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_ap_start : STD_LOGIC;
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_ap_done : STD_LOGIC;
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_ap_idle : STD_LOGIC;
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_ap_ready : STD_LOGIC;
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_img_2_data165_read : STD_LOGIC;
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_img_3_data166_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_img_3_data166_write : STD_LOGIC;
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_2_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_2_ce0 : STD_LOGIC;
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_2_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_2_ce1 : STD_LOGIC;
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_2_we1 : STD_LOGIC;
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_2_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_1_ce0 : STD_LOGIC;
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_1_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_1_ce1 : STD_LOGIC;
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_1_we1 : STD_LOGIC;
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_1_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_ce0 : STD_LOGIC;
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_ce1 : STD_LOGIC;
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_we1 : STD_LOGIC;
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1_fu_139_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal zext_ln541_fu_209_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal icmp_ln1027_2_fu_198_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_col_V_2_fu_90 : STD_LOGIC_VECTOR (12 downto 0);
    signal i_col_V_3_fu_203_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal row_V_fu_94 : STD_LOGIC_VECTOR (12 downto 0);
    signal row_V_3_fu_278_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal empty_50_fu_98 : STD_LOGIC_VECTOR (12 downto 0);
    signal empty_51_fu_102 : STD_LOGIC_VECTOR (12 downto 0);
    signal empty_52_fu_106 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln1027_fu_194_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln1027_1_fu_245_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component color_analysis_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        row_ind_V_2_out : OUT STD_LOGIC_VECTOR (12 downto 0);
        row_ind_V_2_out_ap_vld : OUT STD_LOGIC;
        row_ind_V_1_out : OUT STD_LOGIC_VECTOR (12 downto 0);
        row_ind_V_1_out_ap_vld : OUT STD_LOGIC;
        row_ind_V_out : OUT STD_LOGIC_VECTOR (12 downto 0);
        row_ind_V_out_ap_vld : OUT STD_LOGIC );
    end component;


    component color_analysis_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_2_data165_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_2_data165_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        img_2_data165_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        img_2_data165_empty_n : IN STD_LOGIC;
        img_2_data165_read : OUT STD_LOGIC;
        img_width : IN STD_LOGIC_VECTOR (15 downto 0);
        buf_V_1_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        buf_V_1_ce1 : OUT STD_LOGIC;
        buf_V_1_we1 : OUT STD_LOGIC;
        buf_V_1_d1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component color_analysis_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_2_data165_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_2_data165_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        img_2_data165_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        img_2_data165_empty_n : IN STD_LOGIC;
        img_2_data165_read : OUT STD_LOGIC;
        img_3_data166_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_3_data166_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        img_3_data166_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        img_3_data166_full_n : IN STD_LOGIC;
        img_3_data166_write : OUT STD_LOGIC;
        img_width : IN STD_LOGIC_VECTOR (15 downto 0);
        buf_V_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        buf_V_2_ce0 : OUT STD_LOGIC;
        buf_V_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        buf_V_2_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        buf_V_2_ce1 : OUT STD_LOGIC;
        buf_V_2_we1 : OUT STD_LOGIC;
        buf_V_2_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_V_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        buf_V_1_ce0 : OUT STD_LOGIC;
        buf_V_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        buf_V_1_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        buf_V_1_ce1 : OUT STD_LOGIC;
        buf_V_1_we1 : OUT STD_LOGIC;
        buf_V_1_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        buf_V_ce0 : OUT STD_LOGIC;
        buf_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        buf_V_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        buf_V_ce1 : OUT STD_LOGIC;
        buf_V_we1 : OUT STD_LOGIC;
        buf_V_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_cast1 : IN STD_LOGIC_VECTOR (1 downto 0);
        p_cast2 : IN STD_LOGIC_VECTOR (1 downto 0);
        p_cast : IN STD_LOGIC_VECTOR (1 downto 0);
        cmp_i_i142_i : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component color_analysis_xferode_600_1024_1_0_1_2_2_0_1025_3_3_s_buf_V_RAM_S2P_BRAM_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    buf_V_U : component color_analysis_xferode_600_1024_1_0_1_2_2_0_1025_3_3_s_buf_V_RAM_S2P_BRAM_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_address0,
        ce0 => buf_V_ce0,
        q0 => buf_V_q0,
        address1 => buf_V_address1,
        ce1 => buf_V_ce1,
        we1 => buf_V_we1,
        d1 => buf_V_d1);

    buf_V_1_U : component color_analysis_xferode_600_1024_1_0_1_2_2_0_1025_3_3_s_buf_V_RAM_S2P_BRAM_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_1_address0,
        ce0 => buf_V_1_ce0,
        q0 => buf_V_1_q0,
        address1 => buf_V_1_address1,
        ce1 => buf_V_1_ce1,
        we1 => buf_V_1_we1,
        d1 => buf_V_1_d1);

    buf_V_2_U : component color_analysis_xferode_600_1024_1_0_1_2_2_0_1025_3_3_s_buf_V_RAM_S2P_BRAM_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_2_address0,
        ce0 => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_2_ce0,
        q0 => buf_V_2_q0,
        address1 => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_2_address1,
        ce1 => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_2_ce1,
        we1 => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_2_we1,
        d1 => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_2_d1);

    grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1_fu_139 : component color_analysis_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1_fu_139_ap_start,
        ap_done => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1_fu_139_ap_done,
        ap_idle => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1_fu_139_ap_idle,
        ap_ready => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1_fu_139_ap_ready,
        row_ind_V_2_out => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1_fu_139_row_ind_V_2_out,
        row_ind_V_2_out_ap_vld => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1_fu_139_row_ind_V_2_out_ap_vld,
        row_ind_V_1_out => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1_fu_139_row_ind_V_1_out,
        row_ind_V_1_out_ap_vld => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1_fu_139_row_ind_V_1_out_ap_vld,
        row_ind_V_out => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1_fu_139_row_ind_V_out,
        row_ind_V_out_ap_vld => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1_fu_139_row_ind_V_out_ap_vld);

    grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146 : component color_analysis_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_ap_start,
        ap_done => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_ap_done,
        ap_idle => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_ap_idle,
        ap_ready => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_ap_ready,
        img_2_data165_dout => img_2_data165_dout,
        img_2_data165_num_data_valid => ap_const_lv2_0,
        img_2_data165_fifo_cap => ap_const_lv2_0,
        img_2_data165_empty_n => img_2_data165_empty_n,
        img_2_data165_read => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_img_2_data165_read,
        img_width => img_width,
        buf_V_1_address1 => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_buf_V_1_address1,
        buf_V_1_ce1 => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_buf_V_1_ce1,
        buf_V_1_we1 => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_buf_V_1_we1,
        buf_V_1_d1 => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_buf_V_1_d1);

    grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155 : component color_analysis_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_ap_start,
        ap_done => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_ap_done,
        ap_idle => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_ap_idle,
        ap_ready => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_ap_ready,
        img_2_data165_dout => img_2_data165_dout,
        img_2_data165_num_data_valid => ap_const_lv2_0,
        img_2_data165_fifo_cap => ap_const_lv2_0,
        img_2_data165_empty_n => img_2_data165_empty_n,
        img_2_data165_read => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_img_2_data165_read,
        img_3_data166_din => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_img_3_data166_din,
        img_3_data166_num_data_valid => ap_const_lv2_0,
        img_3_data166_fifo_cap => ap_const_lv2_0,
        img_3_data166_full_n => img_3_data166_full_n,
        img_3_data166_write => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_img_3_data166_write,
        img_width => img_width,
        buf_V_2_address0 => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_2_address0,
        buf_V_2_ce0 => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_2_ce0,
        buf_V_2_q0 => buf_V_2_q0,
        buf_V_2_address1 => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_2_address1,
        buf_V_2_ce1 => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_2_ce1,
        buf_V_2_we1 => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_2_we1,
        buf_V_2_d1 => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_2_d1,
        buf_V_1_address0 => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_1_address0,
        buf_V_1_ce0 => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_1_ce0,
        buf_V_1_q0 => buf_V_1_q0,
        buf_V_1_address1 => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_1_address1,
        buf_V_1_ce1 => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_1_ce1,
        buf_V_1_we1 => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_1_we1,
        buf_V_1_d1 => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_1_d1,
        buf_V_address0 => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_address0,
        buf_V_ce0 => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_ce0,
        buf_V_q0 => buf_V_q0,
        buf_V_address1 => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_address1,
        buf_V_ce1 => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_ce1,
        buf_V_we1 => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_we1,
        buf_V_d1 => grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_d1,
        p_cast1 => empty_54_reg_399,
        p_cast2 => empty_55_reg_404,
        p_cast => empty_53_reg_394,
        cmp_i_i142_i => cmp_i_i142_i_reg_389);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln1027_3_fu_249_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                    grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_ap_ready = ap_const_logic_1)) then 
                    grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1_fu_139_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1_fu_139_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1_fu_139_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1_fu_139_ap_ready = ap_const_logic_1)) then 
                    grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1_fu_139_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln1027_fu_180_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_ap_ready = ap_const_logic_1)) then 
                    grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    empty_50_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) and ((icmp_ln1027_reg_344 = ap_const_lv1_1) or (icmp_ln1027_2_fu_198_p2 = ap_const_lv1_0)))) then 
                empty_50_fu_98 <= grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1_fu_139_row_ind_V_out;
            elsif (((icmp_ln1027_3_fu_249_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                empty_50_fu_98 <= empty_51_fu_102;
            end if; 
        end if;
    end process;

    empty_51_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) and ((icmp_ln1027_reg_344 = ap_const_lv1_1) or (icmp_ln1027_2_fu_198_p2 = ap_const_lv1_0)))) then 
                empty_51_fu_102 <= grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1_fu_139_row_ind_V_1_out;
            elsif (((icmp_ln1027_3_fu_249_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                empty_51_fu_102 <= empty_52_fu_106;
            end if; 
        end if;
    end process;

    empty_52_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) and ((icmp_ln1027_reg_344 = ap_const_lv1_1) or (icmp_ln1027_2_fu_198_p2 = ap_const_lv1_0)))) then 
                empty_52_fu_106 <= grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1_fu_139_row_ind_V_2_out;
            elsif (((icmp_ln1027_3_fu_249_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                empty_52_fu_106 <= empty_50_fu_98;
            end if; 
        end if;
    end process;

    i_col_V_2_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln1027_fu_180_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                i_col_V_2_fu_90 <= ap_const_lv13_0;
            elsif (((icmp_ln1027_reg_344 = ap_const_lv1_0) and (icmp_ln1027_2_fu_198_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                i_col_V_2_fu_90 <= i_col_V_3_fu_203_p2;
            end if; 
        end if;
    end process;

    row_V_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) and ((icmp_ln1027_reg_344 = ap_const_lv1_1) or (icmp_ln1027_2_fu_198_p2 = ap_const_lv1_0)))) then 
                row_V_fu_94 <= ap_const_lv13_1;
            elsif (((icmp_ln1027_3_fu_249_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                row_V_fu_94 <= row_V_3_fu_278_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln1027_3_fu_249_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                cmp_i_i142_i_reg_389 <= cmp_i_i142_i_fu_257_p2;
                empty_53_reg_394 <= empty_53_fu_263_p1;
                empty_54_reg_399 <= empty_54_fu_268_p1;
                empty_55_reg_404 <= empty_55_fu_273_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                icmp_ln1027_reg_344 <= icmp_ln1027_fu_180_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state3, icmp_ln1027_fu_180_p2, icmp_ln1027_reg_344, ap_CS_fsm_state7, icmp_ln1027_3_fu_249_p2, grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1_fu_139_ap_done, grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_ap_done, grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state8, ap_CS_fsm_state6, icmp_ln1027_2_fu_198_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1_fu_139_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln1027_fu_180_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and ((icmp_ln1027_reg_344 = ap_const_lv1_1) or (icmp_ln1027_2_fu_198_p2 = ap_const_lv1_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                if (((icmp_ln1027_3_fu_249_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state8 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state8) and (grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1_fu_139_ap_done)
    begin
        if ((grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1_fu_139_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_ap_done)
    begin
        if ((grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_ap_done)
    begin
        if ((grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state7, icmp_ln1027_3_fu_249_p2)
    begin
        if ((((icmp_ln1027_3_fu_249_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state7, icmp_ln1027_3_fu_249_p2)
    begin
        if (((icmp_ln1027_3_fu_249_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_1_address1_assign_proc : process(grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_buf_V_1_address1, grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_1_address1, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            buf_V_1_address1 <= grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_1_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buf_V_1_address1 <= grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_buf_V_1_address1;
        else 
            buf_V_1_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    buf_V_1_ce0_assign_proc : process(grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_1_ce0, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            buf_V_1_ce0 <= grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_1_ce0;
        else 
            buf_V_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_1_ce1_assign_proc : process(grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_buf_V_1_ce1, grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_1_ce1, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            buf_V_1_ce1 <= grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_1_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buf_V_1_ce1 <= grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_buf_V_1_ce1;
        else 
            buf_V_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_1_d1_assign_proc : process(grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_buf_V_1_d1, grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_1_d1, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            buf_V_1_d1 <= grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_1_d1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buf_V_1_d1 <= grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_buf_V_1_d1;
        else 
            buf_V_1_d1 <= "XXXXXXXX";
        end if; 
    end process;


    buf_V_1_we1_assign_proc : process(grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_buf_V_1_we1, grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_1_we1, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            buf_V_1_we1 <= grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_1_we1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buf_V_1_we1 <= grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_buf_V_1_we1;
        else 
            buf_V_1_we1 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_address1_assign_proc : process(grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_address1, ap_CS_fsm_state8, zext_ln541_fu_209_p1, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            buf_V_address1 <= zext_ln541_fu_209_p1(10 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            buf_V_address1 <= grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_address1;
        else 
            buf_V_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    buf_V_ce0_assign_proc : process(grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_ce0, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            buf_V_ce0 <= grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_ce0;
        else 
            buf_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_ce1_assign_proc : process(grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_ce1, ap_CS_fsm_state8, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            buf_V_ce1 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            buf_V_ce1 <= grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_ce1;
        else 
            buf_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_d1_assign_proc : process(grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_d1, ap_CS_fsm_state8, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            buf_V_d1 <= ap_const_lv8_FF;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            buf_V_d1 <= grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_d1;
        else 
            buf_V_d1 <= "XXXXXXXX";
        end if; 
    end process;


    buf_V_we1_assign_proc : process(icmp_ln1027_reg_344, grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_we1, ap_CS_fsm_state8, ap_CS_fsm_state6, icmp_ln1027_2_fu_198_p2)
    begin
        if (((icmp_ln1027_reg_344 = ap_const_lv1_0) and (icmp_ln1027_2_fu_198_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            buf_V_we1 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            buf_V_we1 <= grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_buf_V_we1;
        else 
            buf_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    cmp_i_i142_i_fu_257_p2 <= "1" when (unsigned(zext_ln1027_1_fu_245_p1) < unsigned(img_height)) else "0";
    empty_53_fu_263_p1 <= empty_52_fu_106(2 - 1 downto 0);
    empty_54_fu_268_p1 <= empty_50_fu_98(2 - 1 downto 0);
    empty_55_fu_273_p1 <= empty_51_fu_102(2 - 1 downto 0);
    grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_ap_start <= grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_ap_start_reg;
    grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1_fu_139_ap_start <= grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_283_1_fu_139_ap_start_reg;
    grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_ap_start <= grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_ap_start_reg;
    i_col_V_3_fu_203_p2 <= std_logic_vector(unsigned(i_col_V_2_fu_90) + unsigned(ap_const_lv13_1));
    icmp_ln1027_2_fu_198_p2 <= "1" when (unsigned(zext_ln1027_fu_194_p1) < unsigned(img_width)) else "0";
    icmp_ln1027_3_fu_249_p2 <= "1" when (unsigned(zext_ln1027_1_fu_245_p1) > unsigned(img_height)) else "0";
    icmp_ln1027_fu_180_p2 <= "1" when (img_width = ap_const_lv16_0) else "0";

    img_2_data165_read_assign_proc : process(grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_img_2_data165_read, grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_img_2_data165_read, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            img_2_data165_read <= grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_img_2_data165_read;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            img_2_data165_read <= grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_VITIS_LOOP_298_2_fu_146_img_2_data165_read;
        else 
            img_2_data165_read <= ap_const_logic_0;
        end if; 
    end process;

    img_3_data166_din <= grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_img_3_data166_din;

    img_3_data166_write_assign_proc : process(grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_img_3_data166_write, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            img_3_data166_write <= grp_xferode_600_1024_1_0_1_2_2_0_1025_3_3_Pipeline_Col_Loop_fu_155_img_3_data166_write;
        else 
            img_3_data166_write <= ap_const_logic_0;
        end if; 
    end process;

    row_V_3_fu_278_p2 <= std_logic_vector(unsigned(row_V_fu_94) + unsigned(ap_const_lv13_1));
    zext_ln1027_1_fu_245_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(row_V_fu_94),16));
    zext_ln1027_fu_194_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_col_V_2_fu_90),16));
    zext_ln541_fu_209_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_col_V_2_fu_90),64));
end behav;
