# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pins.xdc

# Block Designs: bd/sys_design/sys_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_design || ORIG_REF_NAME==sys_design} -quiet] -quiet

# IP: bd/sys_design/ip/sys_design_axi_dynclk_0_0/sys_design_axi_dynclk_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_design_axi_dynclk_0_0 || ORIG_REF_NAME==sys_design_axi_dynclk_0_0} -quiet] -quiet

# IP: bd/sys_design/ip/sys_design_DVI_Transmitter_0_0/sys_design_DVI_Transmitter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_design_DVI_Transmitter_0_0 || ORIG_REF_NAME==sys_design_DVI_Transmitter_0_0} -quiet] -quiet

# IP: bd/sys_design/ip/sys_design_capture_rgb565_data_0_0/sys_design_capture_rgb565_data_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_design_capture_rgb565_data_0_0 || ORIG_REF_NAME==sys_design_capture_rgb565_data_0_0} -quiet] -quiet

# IP: bd/sys_design/ip/sys_design_axi_smc_0/sys_design_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_design_axi_smc_0 || ORIG_REF_NAME==sys_design_axi_smc_0} -quiet] -quiet

# Block Designs: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/bd_ce02.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_0/bd_ce02_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_1/bd_ce02_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_2/bd_ce02_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_3/bd_ce02_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_4/bd_ce02_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_5/bd_ce02_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_6/bd_ce02_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_7/bd_ce02_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_8/bd_ce02_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_9/bd_ce02_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_10/bd_ce02_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_11/bd_ce02_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_12/bd_ce02_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_13/bd_ce02_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_14/bd_ce02_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_15/bd_ce02_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_16/bd_ce02_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_17/bd_ce02_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_18/bd_ce02_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_19/bd_ce02_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_20/bd_ce02_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_21/bd_ce02_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_22/bd_ce02_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_23/bd_ce02_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_24/bd_ce02_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_25/bd_ce02_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_26/bd_ce02_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_design/ip/sys_design_axi_vdma_0_0/sys_design_axi_vdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_design_axi_vdma_0_0 || ORIG_REF_NAME==sys_design_axi_vdma_0_0} -quiet] -quiet

# IP: bd/sys_design/ip/sys_design_processing_system7_0_0/sys_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_design_processing_system7_0_0 || ORIG_REF_NAME==sys_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/sys_design/ip/sys_design_xbar_0/sys_design_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_design_xbar_0 || ORIG_REF_NAME==sys_design_xbar_0} -quiet] -quiet

# IP: bd/sys_design/ip/sys_design_ps7_0_axi_periph_0/sys_design_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==sys_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/sys_design/ip/sys_design_rst_ps7_0_100M_0/sys_design_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==sys_design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/sys_design/ip/sys_design_v_axi4s_vid_out_0_0/sys_design_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_design_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==sys_design_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/sys_design/ip/sys_design_v_tc_0_0/sys_design_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_design_v_tc_0_0 || ORIG_REF_NAME==sys_design_v_tc_0_0} -quiet] -quiet

# IP: bd/sys_design/ip/sys_design_v_vid_in_axi4s_0_0/sys_design_v_vid_in_axi4s_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_design_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==sys_design_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: bd/sys_design/ip/sys_design_color_analysis_0_0/sys_design_color_analysis_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_design_color_analysis_0_0 || ORIG_REF_NAME==sys_design_color_analysis_0_0} -quiet] -quiet

# IP: bd/sys_design/ip/sys_design_axi_bram_ctrl_0_0/sys_design_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_design_axi_bram_ctrl_0_0 || ORIG_REF_NAME==sys_design_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/sys_design/ip/sys_design_blk_mem_gen_0_0/sys_design_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_design_blk_mem_gen_0_0 || ORIG_REF_NAME==sys_design_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/sys_design/ip/sys_design_test_Hu_0_0/sys_design_test_Hu_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_design_test_Hu_0_0 || ORIG_REF_NAME==sys_design_test_Hu_0_0} -quiet] -quiet

# IP: bd/sys_design/ip/sys_design_CAL_Hu_0_0/sys_design_CAL_Hu_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_design_CAL_Hu_0_0 || ORIG_REF_NAME==sys_design_CAL_Hu_0_0} -quiet] -quiet

# IP: bd/sys_design/ip/sys_design_auto_pc_7/sys_design_auto_pc_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_design_auto_pc_7 || ORIG_REF_NAME==sys_design_auto_pc_7} -quiet] -quiet

# IP: bd/sys_design/ip/sys_design_auto_pc_0/sys_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_design_auto_pc_0 || ORIG_REF_NAME==sys_design_auto_pc_0} -quiet] -quiet

# IP: bd/sys_design/ip/sys_design_auto_pc_1/sys_design_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_design_auto_pc_1 || ORIG_REF_NAME==sys_design_auto_pc_1} -quiet] -quiet

# IP: bd/sys_design/ip/sys_design_auto_pc_2/sys_design_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_design_auto_pc_2 || ORIG_REF_NAME==sys_design_auto_pc_2} -quiet] -quiet

# IP: bd/sys_design/ip/sys_design_auto_pc_3/sys_design_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_design_auto_pc_3 || ORIG_REF_NAME==sys_design_auto_pc_3} -quiet] -quiet

# IP: bd/sys_design/ip/sys_design_auto_pc_4/sys_design_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_design_auto_pc_4 || ORIG_REF_NAME==sys_design_auto_pc_4} -quiet] -quiet

# IP: bd/sys_design/ip/sys_design_auto_pc_5/sys_design_auto_pc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_design_auto_pc_5 || ORIG_REF_NAME==sys_design_auto_pc_5} -quiet] -quiet

# IP: bd/sys_design/ip/sys_design_auto_pc_6/sys_design_auto_pc_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_design_auto_pc_6 || ORIG_REF_NAME==sys_design_auto_pc_6} -quiet] -quiet

# IP: bd/sys_design/ip/sys_design_s01_mmu_0/sys_design_s01_mmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_design_s01_mmu_0 || ORIG_REF_NAME==sys_design_s01_mmu_0} -quiet] -quiet

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_1/bd_ce02_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_1/bd_ce02_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_2/bd_ce02_arsw_0_ooc.xdc

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_3/bd_ce02_rsw_0_ooc.xdc

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_4/bd_ce02_awsw_0_ooc.xdc

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_5/bd_ce02_wsw_0_ooc.xdc

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_6/bd_ce02_bsw_0_ooc.xdc

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_10/bd_ce02_s00a2s_0_ooc.xdc

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_11/bd_ce02_sarn_0_ooc.xdc

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_12/bd_ce02_srn_0_ooc.xdc

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_16/bd_ce02_s01a2s_0_ooc.xdc

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_17/bd_ce02_sawn_0_ooc.xdc

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_18/bd_ce02_swn_0_ooc.xdc

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_19/bd_ce02_sbn_0_ooc.xdc

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_20/bd_ce02_m00s2a_0_ooc.xdc

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_21/bd_ce02_m00arn_0_ooc.xdc

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_22/bd_ce02_m00rn_0_ooc.xdc

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_23/bd_ce02_m00awn_0_ooc.xdc

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_24/bd_ce02_m00wn_0_ooc.xdc

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/bd_0/ip/ip_25/bd_ce02_m00bn_0_ooc.xdc

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_smc_0/ooc.xdc

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_vdma_0_0/sys_design_axi_vdma_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==sys_design_axi_vdma_0_0 || ORIG_REF_NAME==sys_design_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_vdma_0_0/sys_design_axi_vdma_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==sys_design_axi_vdma_0_0 || ORIG_REF_NAME==sys_design_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_axi_vdma_0_0/sys_design_axi_vdma_0_0_ooc.xdc

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_processing_system7_0_0/sys_design_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==sys_design_processing_system7_0_0 || ORIG_REF_NAME==sys_design_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_rst_ps7_0_100M_0/sys_design_rst_ps7_0_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==sys_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==sys_design_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_rst_ps7_0_100M_0/sys_design_rst_ps7_0_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==sys_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==sys_design_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_v_axi4s_vid_out_0_0/sys_design_v_axi4s_vid_out_0_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==sys_design_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==sys_design_v_axi4s_vid_out_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_v_tc_0_0/sys_design_v_tc_0_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==sys_design_v_tc_0_0 || ORIG_REF_NAME==sys_design_v_tc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_v_vid_in_axi4s_0_0/sys_design_v_vid_in_axi4s_0_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==sys_design_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==sys_design_v_vid_in_axi4s_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_color_analysis_0_0/constraints/color_analysis_ooc.xdc

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_blk_mem_gen_0_0/sys_design_blk_mem_gen_0_0_ooc.xdc

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_test_Hu_0_0/constraints/test_Hu_ooc.xdc

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_CAL_Hu_0_0/constraints/CAL_Hu_ooc.xdc

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_auto_pc_7/sys_design_auto_pc_7_ooc.xdc

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_auto_pc_0/sys_design_auto_pc_0_ooc.xdc

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_auto_pc_1/sys_design_auto_pc_1_ooc.xdc

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_auto_pc_2/sys_design_auto_pc_2_ooc.xdc

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_auto_pc_3/sys_design_auto_pc_3_ooc.xdc

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_auto_pc_4/sys_design_auto_pc_4_ooc.xdc

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_auto_pc_5/sys_design_auto_pc_5_ooc.xdc

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/ip/sys_design_auto_pc_6/sys_design_auto_pc_6_ooc.xdc

# XDC: d:/Program_File/HLS_Files/cap_rgb565_demo/cap_rgb565_demo.gen/sources_1/bd/sys_design/sys_design_ooc.xdc
